fint:
  kafka:
    topic:
      org-id: fintlabs.no
      domain-context: flyt
    application-id: fint-flyt-test-dispatch-gateway
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-flyt-test-dispatch-gateway
server:
  port: 8080